[workspace]
members = [
    "kernel"
]

[build-dependencies]
bootloader = "*"
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }


[package]
name = "nocciolo"
version = "0.1.1"
edition = "2021"

