[package]
name = "nocciolo"
version = "0.1.1"
edition = "2021"

[build-dependencies]
bootloader = "0.11.7"
nocciolo-kernel = { path = "../kernel", artifact = "bin", target="x86_64-unknown-none" }

[dependencies]
ovmf-prebuilt = "0.1.0-alpha.1"
which = "6"
